#!/bin/sh
set -e

case "$1" in
    purge)
        if getent passwd oati-ts-monitor >/dev/null 2>&1; then
            deluser oati-ts-monitor || true
        fi
        if getent group oati-ts-monitor >/dev/null 2>&1; then
            delgroup oati-ts-monitor || true
        fi
        ;;
esac

# Automatically added by dh_installsystemd/13.11.4
if [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.11.4
if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'oati-ts-monitor.service' >/dev/null || true
	fi
fi
# End automatically added section


exit 0
