#!/bin/sh
set -e

case "$1" in
    configure)
        if ! getent group oati-ts-monitor >/dev/null 2>&1; then
            addgroup --system oati-ts-monitor || true
        fi
        if ! getent passwd oati-ts-monitor >/dev/null 2>&1; then
            adduser --system --ingroup oati-ts-monitor --home /var/lib/oati-ts-monitor \
                --no-create-home --disabled-login oati-ts-monitor || true
        fi
        install -d -o oati-ts-monitor -g oati-ts-monitor -m 0750 /var/lib/oati-ts-monitor
        install -d -o oati-ts-monitor -g oati-ts-monitor -m 0750 /var/log/oati-ts-monitor
        install -d -o oati-ts-monitor -g oati-ts-monitor -m 0750 /var/lib/oati-ts-monitor/wifilogs
        install -d -o oati-ts-monitor -g oati-ts-monitor -m 0750 /var/lib/oati-ts-monitor/logs
        chown -R oati-ts-monitor:oati-ts-monitor /var/lib/oati-ts-monitor /var/log/oati-ts-monitor || true
        ;;
esac

# Automatically added by dh_installsystemd/13.11.4
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	# The following line should be removed in trixie or trixie+1
	deb-systemd-helper unmask 'oati-ts-monitor.service' >/dev/null || true

	# was-enabled defaults to true, so new installations run enable.
	if deb-systemd-helper --quiet was-enabled 'oati-ts-monitor.service'; then
		# Enables the unit on first installation, creates new
		# symlinks on upgrades if the unit file has changed.
		deb-systemd-helper enable 'oati-ts-monitor.service' >/dev/null || true
	else
		# Update the statefile to add new symlinks (if any), which need to be
		# cleaned up on purge. Also remove old symlinks.
		deb-systemd-helper update-state 'oati-ts-monitor.service' >/dev/null || true
	fi
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.11.4
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -d /run/systemd/system ]; then
		systemctl --system daemon-reload >/dev/null || true
		if [ -n "$2" ]; then
			_dh_action=restart
		else
			_dh_action=start
		fi
		deb-systemd-invoke $_dh_action 'oati-ts-monitor.service' >/dev/null || true
	fi
fi
# End automatically added section


exit 0
